<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Roms_Web-09818b76-9b27-4d40-a4ab-090aebdcd055</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App.Internal.Assets" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Data\Migrations\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Roms.Domain\Roms.Domain.csproj" />
    <ProjectReference Include="..\Roms.Application\Roms.Application.csproj" />
    <ProjectReference Include="..\Roms.Infrastructure\Roms.Infrastructure.csproj" />
  </ItemGroup>

</Project>
